### ISSUE TITLE
The random automated tests on the random_tests branch are failing

### ISSUE THREAD

**Issue by JaderDias** [JaderDias/movingmedian#1]

**Comment by JaderDias** [comment]
tested every single commit from https://github.com/JaderDias/movingmedian/commit/d661031ac5a580afe27673c3b90f5814592e27ed until the most recent ones, and all of them fail the random tests

**Comment by dgryski** [comment]
Can you try a dumber implementation of the 'right' answer? Perhaps the test is broken.

**Comment by dgryski** [comment]
Addressed in #2

**Comment by dgryski** [comment]
#2 is merged, randomized tests found bugs which are now fixed.
